//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Depot
    {
        public Depot()
        {
            this.Customers = new HashSet<Customer>();
            this.Products = new HashSet<Product>();
        }
    
        public int DepotId { get; set; }
        public int LocationLocationId { get; set; }
    
        public virtual ICollection<Customer> Customers { get; set; }
        public virtual ICollection<Product> Products { get; set; }
        public virtual Location Location { get; set; }
    }
}
